name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: |
            echo "1 output"
            echo "2 output"
            echo "3 output"
            echo "4 output"
      
